CREATE DATABASE pj_prac;

USE pj_prac;

CREATE TABLE dapp_info(
    idx int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    account VARCHAR(100) NOT NULL,
    img VARCHAR(100) NOT NULL,
    files VARCHAR(100) NOT NULL,
    explains VARCHAR(100) NOT NULL
);